### PR TITLE
Many small changes to updater.py

### PR DESCRIPTION
**Pull request by genodeftest**
Some work on updater.py, probably perfectionistic ;)

Not ready to merge yet, there is still one issue with printing to the wrong command line (see [my question on the mailing list](https://mail.gnome.org/archives/python-hackers-list/2016-May/msg00008.html). I'm just opening this here so that you know what's going on and – hopefully – don't merge a conflicting change to updater.py at the same time.

For reasons for those changes, please have a look at commit descriptions.

### CODE REVIEW

**Comment by genodeftest** [comment]
Now ready to merge in my opinion. @timlau?

**Comment by timlau** [comment]
Looks fine to me

The only minor issue is:
Why the the double `_`   on local vars (ex. self.`__`somevars), normally a singe `_` is used to mark somthing private.
Double `_` is normally only used for `__init__` type of methods.
I use a single `_` private methods/vars in other parts of the code, so you should problerly also do this for consistancy.

**EDIT**
Just checked the official docs, `__` os used to protect a var/method from being overloaded in a child class, and `_` is used to mark at method or var af non public API.
As far as I can see there is no need to use `__` in this code
https://docs.python.org/3.4/tutorial/classes.html#tut-private

**Comment by genodeftest** [comment]
Yes, I understand `__` (double underscore) as marking it "private" and `_` (single underscore) as marking it `protected` to speak in Java terms.
Since we're not using inheritation here, both have the same effect, so it should not matter. Right?

**Comment by timlau** [comment]
It does not matter from a functional point of view, just about consistancy
feel free to merge it

**Pull request merged**
