### PR TITLE
Change font colors if using dark theme

### PR DESCRIPTION
**Pull request by tamimym**
I created a function that checks if gtk is using a dark theme. In which case, I adjust the colors so that they become readable.
Here's a screenshot of the finished work.

screenshot from 2015-07-28 23-21-56

### CODE REVIEW

**Comment by rapgro** [comment]
Cool feature, thanks. :+1: 
Although, yumex-dnf should prefer font settings from the currently applied theme, so your gtk theme propably have to use readable fonts.

**Comment by timlau** [comment]
Merged, Thanks

**Comment by genodeftest** [comment]
These changes break font color on light themes. All black fonts (available packages) are now white which is unusable on a light Gtk3 theme.
The check you added (check_dark_theme) is correctly detecting a light theme. Everything else (background color, green fonts for installed packages, …) is working fine though.

**Comment by timlau** [comment]
There was a bug, I have fixed it

https://github.com/timlau/yumex-dnf/commit/0313edf9a7b3d3c7bac23e0d9ef03ffd824de630

**Comment by timlau** [comment]
Agree, this is a work around and a better way is to get  colors from the theme.

yumex-dnf has a feature so a theme author can supply a speciel .css file to configue the look and feel of yumex-dnf

(See #26 for details)

**Pull request merged**
