### PR TITLE
InfoBar: remove custom colors and code

### LINKED ISSUE #87: Yumex-Dnf Status Bar Text Colour
I've begun using Yumex-DNF in the past while. I like it because the program updates list font size is larger than in Yumex.

One thing that should be fixed is the font colour of the status bar "Downloading..." "Applying changes..." part of the program.

Perhaps it's just my setup, but the status bar text is in medium grey on a black background. This is very difficult to see, without having to go up close to my monitor screen.

### PR DESCRIPTION
**Pull request by genodeftest**
Rely on Gtk theme for coloring the info bar.
Use a GtkInfoBar.

This will fix #87.

### CODE REVIEW

**Comment by timlau** [comment]
tnx, merged

**Comment by timlau** [comment]
screenshot from 2016-04-28 09-44-20

**Comment by timlau** [comment]
@genodeftest , Looks like the Infobar type need to be changed, I get a blue background

**Comment by genodeftest** [comment]
Just change it to any type you want. I did that intentionally, to be consistent with e.g. gedit's progress bar when loading documents. I don't care much about it though.

**Comment by timlau** [comment]
Ok, I will test it a little, was not sure the it was on purpose :-)

**Comment by timlau** [comment]
Just updated my system to F25, there is some problems with the progress bar, it only is shown the fist time, have you tested on F25

**Comment by timlau** [comment]
https://github.com/timlau/yumex-dnf/commit/7d2cf9ddd98b4dd386409d4af3c24e4b10476977

Fixed it, we need the Gtk.Revealer to make the infobar behave

**Comment by genodeftest** [comment]
> Just updated my system to F25, there is some problems with the progress bar, it only is shown the fist time, have you tested on F25

No. I was running F24 with Gtk+ 3.20 and it worked fine. Still works fine on F24 with your changes.

**Pull request merged**
